### ISSUE TITLE
Infografia 1. Erik Cuevas

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-1-infografia-ErikCuevas03#1]
[Ciclo de vida de dasrrollo de software.pdf](https://github.com/user-attachments/files/16821382/Ciclo.de.vida.de.dasrrollo.de.software.pdf)

**Comment by Jaczibeth** [comment]
De acuerdo a la rúbrica tienes el 18 %
presentas faltas de ortografía, faltan referencias......

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
